overwrite: true
schema: 'http://localhost:3000/api'
documents: './src/lib/schemas/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
